# fly.toml app configuration file generated for dashfloat-staging on 2023-11-20T11:53:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dashfloat-staging"
primary_region = "sin"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "staging.dashfloat.com"
  PORT = "8080"
  MAIL_HOST = "dashfloat.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
